<?php

namespace App\Enums;

enum ActivityType: string
{
    case LOGIN = 'LOGIN';
    case LOGOUT = 'LOGOUT';
    case LOAN_CREATED = 'LOAN_CREATED';
    case LOAN_UPDATED = 'LOAN_UPDATED';
    case CLAIM_CREATED = 'CLAIM_CREATED';
    case CLAIM_UPDATED = 'CLAIM_UPDATED';
    case PAYMENT_MADE = 'PAYMENT_MADE';
    case REGISTRATION = 'REGISTRATION';
    case BULK_LOAN_IMPORT = 'BULK_LOAN_IMPORT';
    case PREMIUM_DEDUCTED = 'PREMIUM_DEDUCTED';
    case PREMIUM_CREDITED = 'PREMIUM_CREDITED';
    case ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED';
    case ACCOUNT_ACTIVATED = 'ACCOUNT_ACTIVATED';
}
